version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: merchshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: merchshop-api
    build:
      context: .
      dockerfile: MerchShop.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
    ports:
      - "5008:5008"
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...';
        until pg_isready -h postgres -p 5432 -U postgres; do
          echo 'Waiting for PostgreSQL...';
          sleep 2;
        done;
        dotnet ef migrations add init --no-build || true &&
        dotnet ef database update &&
        dotnet run"

volumes:
  postgres-data:
