FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MerchShop.API/MerchShop.API.csproj", "MerchShop.API/"]
COPY ["MerchShop.Infrastructure/MerchShop.Infrastructure.csproj", "MerchShop.Infrastructure/"]
RUN dotnet restore "MerchShop.API/MerchShop.API.csproj"
COPY . .
WORKDIR "/src/MerchShop.API"
RUN dotnet build "MerchShop.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "MerchShop.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY init-migrations.sh /app/init-migrations.sh

ENTRYPOINT ["./init-migrations.sh"]